### ISSUE TITLE
formatting of graph inaccurate 

### ISSUE THREAD

**Issue by kcw-grunt** [elaineo/FollowerFactory#5]
Thanks for this @elaineo but when I view the index.html, I only see the points in a straight line.  I'm trying to learn but I hoped you could help me locate the bug.  It is in index.html (data.csv is fine):

<img width="924" alt="screen shot 2018-01-31 at 11 39 57 am" src="https://user-images.githubusercontent.com/2899463/35643563-8d65a15a-067b-11e8-94d1-63721572673e.png">

**Comment by elaineo** [comment]
what does `data.csv` contain?

**Comment by kcw-grunt** [comment]
```
close,date
911956627204456448,Sun Sep 24 14:12:58 +0000 2017 
2667650047,Tue Jul 22 00:39:03 +0000 2014 
927554270701830145,Mon Nov 06 15:12:26 +0000 2017 
926837440660365312,Sat Nov 04 15:44:00 +0000 2017 
922144003411324929,Sun Oct 22 16:53:57 +0000 2017 
889925943426461696,Tue Jul 25 19:10:53 +0000 2017 
909108862598434816,Sat Sep 16 17:36:58 +0000 2017 
906595619439038465,Sat Sep 09 19:10:14 +0000 2017 
897875850305187840,Wed Aug 16 17:40:59 +0000 2017 
329851836,Tue Jul 05 18:29:23 +0000 2011 
821366968640880640,Tue Jan 17 14:42:00 +0000 2017 
894538672128872448,Mon Aug 07 12:40:13 +0000 2017 
894310633939894273,Sun Aug 06 21:34:05 +0000 2017 
23969177,Thu Mar 12 15:38:33 +0000 2009 
180083054,Wed Aug 18 20:09:05 +0000 2010 
880803242044555265,Fri Jun 30 15:00:32 +0000 2017 
878019146679820293,Thu Jun 22 22:37:32 +0000 2017 
872265853701697536,Wed Jun 07 01:36:00 +0000 2017 
869881741787443200,Wed May 31 11:42:23 +0000 2017 
459214647,Mon Jan 09 12:11:43 +0000 2012 
837832502844719104,Sat Mar 04 01:10:09 +0000 2017 
2308932576,Fri Jan 24 20:39:20 +0000 2014 
879043141,Sun Oct 14 00:59:46 +0000 2012 
834640457632202752,Thu Feb 23 05:46:06 +0000 2017 
851151996371562496,Sun Apr 09 19:17:04 +0000 2017 
....

```

**Comment by elaineo** [comment]
oh, i see. this change https://github.com/elaineo/FollowerFactory/commit/a96610e2f2d8c404a8fd23d74d781a2a916310b5 caused a problem. 

Line 28  of `index.html` should have a space at the end, ie `d3.timeParse("%a %b %d %H:%M:%S %Z %Y ");`

[Here.](https://github.com/elaineo/FollowerFactory/blob/master/index.html#L28)

**Comment by kcw-grunt** [comment]
Ok..thanks!  want a PR? (j/k)

**Comment by elaineo** [comment]
i reverted that change so it should be ok now, thanks for reporting :)

**Comment by kcw-grunt** [comment]
<img width="954" alt="screen shot 2018-01-31 at 11 55 00 am" src="https://user-images.githubusercontent.com/2899463/35644365-9db7795a-067d-11e8-8e78-b77538c98fb8.png">

**Comment by kcw-grunt** [comment]
its a neat project..thanks for posting

**Comment by captbaritone** [comment]
This fixed the problem for me as well. Great project!

**Comment by lseemann** [comment]
This is a fun tool. Thanks for building it!

I suggested removing the trailing space from the timeParse argument because it was causing my chart to have the same borked y axis that kcw-grunt observed. Only by removing it was I able to get a correct scatterplot. ¯\_(ツ)_/¯
