### ISSUE TITLE
TwitterAPI timeout

### ISSUE THREAD

**Issue by lseemann** [elaineo/FollowerFactory#6]
I keep getting a “Read timed out,” always around the same spot (count 6400). 

```
INFO:root:count: 6400
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.twitter.com
WARNING:root:<class 'requests.exceptions.ReadTimeout'> HTTPSConnectionPool(host='api.twitter.com', port=443): Read timed out. (read timeout=5)
Traceback (most recent call last):
  File "ff.py", line 43, in <module>
    main()
  File "ff.py", line 28, in main
    fans_raw = bot.request('followers/list', {'screen_name': SCREEN_NAME, 'count': 200, 'cursor':cursor, 'skip_status':True, 'include_user_entities': False})
  File "/Library/Python/2.7/site-packages/TwitterAPI/TwitterAPI.py", line 134, in request
    raise TwitterConnectionError(e)
TwitterAPI.TwitterError.TwitterConnectionError: HTTPSConnectionPool(host='api.twitter.com', port=443): Read timed out. (read timeout=5)
```

**Comment by elaineo** [comment]
You can pick up where you left off by changing `cursor` and `count` to the last value printed out before the error, and commenting out line 22-23. There's not much you can do about Twitter connection errors, unfortunately.

**Comment by lseemann** [comment]
FWIW, I kept getting the timeout around the same point on the same account, whereas on other accounts I kept merrily crawling along for hours and hours. I briefly changed the count interval from 200 to 50 and that seems to have gotten it over the hump.

**Comment by barripdmx** [comment]
Same problem. Change to 50 to see what happens.

**Comment by barripdmx** [comment]
Another error :( 
Solution?

> INFO:root:count: 110600
> WARNING:root:<class 'requests.exceptions.ConnectTimeout'> HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json?count=200&cursor=1554263394255104074&include_user_entities=False&screen_name=movistar_es&skip_status=True (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000004259F60>, 'Connection to api.twitter.com timed out. (connect timeout=5)'))
> Traceback (most recent call last):
>   File "ff.py", line 43, in <module>
>     main()
>   File "ff.py", line 28, in main
>     fans_raw = bot.request('followers/list', {'screen_name': SCREEN_NAME, 'count': 200, 'cursor':cursor, 'skip_status':True, 'include_user_entities': False})
>   File "C:\python27\TwitterAPI\TwitterAPI.py", line 140, in request
>     raise TwitterConnectionError(e)
> TwitterAPI.TwitterError.TwitterConnectionError: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/followers/list.json?count=200&cursor=1554263394255104074&include_user_entities=False&screen_name=movistar_es&skip_status=True (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000004259F60>, 'Connection to api.twitter.com timed out. (connect timeout=5)'))

**Comment by elaineo** [comment]
the connection to Twitter is failing. can you reach api.twitter.com at all?
